### ISSUE TITLE
minter.mo - about minter new WTC when recept ICP

### ISSUE THREAD

**Issue by LevenSton** [Toniq-Labs/wrapped_cycles#1]
if (cyclesAtStart < Cycles.balance()){
          //Get out
          
          _errors := Array.append(_errors, ["3"]);
          return #Err("Cycles exhausted");
        } else {
          let newCycles : Nat = cyclesAtStart - Cycles.balance();
.......
}

in func transaction_notification minter.mo,,, after sended ICP to CYCLES_MINTER canister, Does Cycles.balance() > cyclesAtStart.???,   why  cyclesAtStart < Cycles.balance()?  thanks

**Comment by stephenandrews** [comment]
Because the amount added is less than the amount used to process the msg
